services:

#  gateway:
#    image: ghcr.io/pawissanutt/oaas/gateway
#    # network_mode: host
#    depends_on:
#      - dev-pm
#    ports:
#      - "10000:10000"
#    environment:
#      HTTP_PORT: 10000
#      RUST_LOG: INFO
#      OPRC_PM_URI: http://dev-pm:10002
#      OPRC_MAX_POOL_SIZE: 256


  odgm:
    # network_mode: host
    image: ghcr.io/pawissanutt/oaas/odgm
    ports:
      - "10001:10001"
      - "17447:17447"
    environment:
      ODGM_LOG: DEBUG,openraft=info,h2=warn
      ODGM_HTTP_PORT: 10001
      OPRC_ZENOH_PORT: 17447
      ODGM_NODE_ID: 1
      ODGM_COLLECTION: |
        [
          {"name":"example.hello","partition_count":1,"replica_count":1,"shard_assignments":[{"primary": 1, "replica":[1],"shard_ids":[1]}], 
            "invocations": {
              "fn_routes": {
                "new": {"url":"http://hello-fn:8080", "stateless": true, "standby": false, "active_group":[]},
                "greet": {"url":"http://hello-fn:8080", "stateless": false, "standby": false, "active_group":[]},
                "echo": {"url":"http://hello-fn:8080", "stateless": true, "standby": false, "active_group":[]}
              }
            },
            "shard_type":"basic","options":{}
          },
          {"name":"example.record","partition_count":1,"replica_count":1,"shard_assignments":[{"primary": 1, "replica":[1],"shard_ids":[1]}], 
            "invocations": {
              "fn_routes": {
                "random": {"url":"http://hello-fn:8080", "stateless": false, "standby": false, "active_group":[]}
              }
            },
            "shard_type":"basic","options":{}
          }
        ]

#  dev-pm:
#    # network_mode: host
#    image: ghcr.io/pawissanutt/oaas/dev-pm
#    ports:
#      - "10002:10002"
#    environment:
#      HTTP_PORT: 10002
#      RUST_LOG: INFO
#      PM_CLS_LIST: example.hello!new=http://hello-fn:8080|greet=http://hello-fn:8080|talk=http://hello-fn:8080|change_intro=http://hello-fn:8080

  
  hello-fn:
    build:
      context: .
      dockerfile: dev.Dockerfile
      # args:
      #   APP_DIR: helloworld
    command: "'poetry sync && poetry run python -m examples.helloworld.helloworld'"
    entrypoint: ["/bin/bash", "-c"]
    image: harbor.129.114.109.85.nip.io/oaas/hello-fn-dev
    environment:
      OPRC_ODGM_URL: http://odgm:10001
      POETRY_VIRTUALENVS_PATH: /opt/venvs
    volumes:
      - .:/app
      - poetry-cache:/app/.cache
      - envs:/opt/venvs

volumes:
  poetry-cache:
  envs: