services:


  odgm:
    # network_mode: host
    image: ghcr.io/pawissanutt/oaas-rs/odgm
    ports:
      - "10001:10001"
      - "17447:17447"
    environment:
      ODGM_LOG: DEBUG,openraft=info,h2=warn
      ODGM_HTTP_PORT: 10001
      OPRC_ZENOH_PORT: 17447
      ODGM_MAX_SESSIONS: 1
      ODGM_NODE_ID: 1
      OPRC_ZENOH_PEERS: tcp/router:7447
      ODGM_COLLECTION: |
        [
          {"name":"example.hello","partition_count":1,"replica_count":1,"shard_assignments":[{"primary": 1, "replica":[1],"shard_ids":[1]}], 
            "invocations": {
              "fn_routes": {
                "new": {"url":"http://hello-fn:8080", "stateless": true, "standby": false, "active_group":[]},
                "greet": {"url":"http://hello-fn:8080", "stateless": false, "standby": false, "active_group":[]},
                "echo": {"url":"http://hello-fn:8080", "stateless": true, "standby": false, "active_group":[]}
              }
            },
            "shard_type":"basic","options":{}
          },
          {"name":"example.record","partition_count":1,"replica_count":1,"shard_assignments":[{"primary": 1, "replica":[1],"shard_ids":[2]}], 
            "invocations": {
              "fn_routes": {
                "random": {"url":"http://hello-fn:8080", "stateless": false, "standby": false, "active_group":[]}
              }
            },
            "shard_type":"basic","options":{}
          }
        ]

  router:
    deploy:
      replicas: 1
    image: ghcr.io/pawissanutt/oaas-rs/router
    # network_mode: "host"
    ports:
      - "7447:7447"
    environment:
      OPRC_LOG: "INFO"
      OPRC_ZENOH_PORT: "7447"


  
  hello-fn:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "10002:8080"
    environment:
      OPRC_ODGM_URL: http://odgm:10001
      OPRC_ZENOH_PEERS: tcp/router:7447
      LOG_LEVEL: DEBUG
      RUST_LOG: info
      APP_DIR: /app/helloworld
    volumes:
      - ./examples/helloworld:/app/helloworld
    

volumes:
  poetry-cache:
  envs: