services:

#  gateway:
#    image: ghcr.io/pawissanutt/oaas/gateway
#    # network_mode: host
#    depends_on:
#      - dev-pm
#    ports:
#      - "10000:10000"
#    environment:
#      HTTP_PORT: 10000
#      RUST_LOG: INFO
#      OPRC_PM_URI: http://dev-pm:10002
#      OPRC_MAX_POOL_SIZE: 256


  odgm:
    # network_mode: host
    image: ghcr.io/pawissanutt/oaas-rs/odgm
    ports:
      - "10001:10001"
      # - "17447:17447"
    environment:
      ODGM_LOG: DEBUG,openraft=info,h2=warn
      ODGM_HTTP_PORT: 10001
      # OPRC_ZENOH_PORT: 17447
      ODGM_NODE_ID: 1
      ODGM_COLLECTION: |
        [
          {"name":"example.hello","partition_count":1,"replica_count":1,"shard_assignments":[{"primary": 1, "replica":[1],"shard_ids":[1]}], 
            "invocations": {
              "fn_routes": {
                "new": {"url":"http://hello-fn:8080", "stateless": true, "standby": false, "active_group":[]},
                "greet": {"url":"http://hello-fn:8080", "stateless": false, "standby": false, "active_group":[]},
                "echo": {"url":"http://hello-fn:8080", "stateless": true, "standby": false, "active_group":[]}
              }
            },
            "shard_type":"basic","options":{}
          },
          {"name":"example.record","partition_count":1,"replica_count":1,"shard_assignments":[{"primary": 1, "replica":[1],"shard_ids":[1]}], 
            "invocations": {
              "fn_routes": {
                "random": {"url":"http://hello-fn:8080", "stateless": false, "standby": false, "active_group":[]}
              }
            },
            "shard_type":"basic","options":{}
          }
        ]

  router:
    deploy:
      replicas: 1
    image: ghcr.io/pawissanutt/oaas-rs/router
    # network_mode: "host"
    ports:
      - "7447:7447"
    environment:
      OPRC_LOG: "INFO"
      OPRC_ZENOH_PORT: "7447"
#  dev-pm:
#    # network_mode: host
#    image: ghcr.io/pawissanutt/oaas/dev-pm
#    ports:
#      - "10002:10002"
#    environment:
#      HTTP_PORT: 10002
#      RUST_LOG: INFO
#      PM_CLS_LIST: example.hello!new=http://hello-fn:8080|greet=http://hello-fn:8080|talk=http://hello-fn:8080|change_intro=http://hello-fn:8080

  
  hello-fn:
    build:
      context: .
      dockerfile: examples/Dockerfile
      args:
        APP_DIR: examples.helloworld
    # command: "'uv sync && uv run python -m examples.helloworld'"
    # entrypoint: ["/bin/bash", "-c"]
    ports:
      - "10002:8080"
    environment:
      OPRC_ODGM_URL: http://odgm:10001
      LOG_LEVEL: DEBUG

volumes:
  poetry-cache:
  envs: