cri:="podman"

build:
    {{cri}} compose build
#    {{cri}} build . --build-arg APP_DIR=helloword -t harbor.129.114.109.85.nip.io/oaas/hello-fn

push: build
    {{cri}} push harbor.129.114.109.85.nip.io/oaas/hello-fn


