[project]
name = "oaas-sdk2-py-example"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "oaas-sdk2-py>=0.2.1",
    "psutil>=7.0.0",
]

[tool.uv]
prerelease = "allow"

